control/urls.py
from django.conf.urls import url
from control import views

urlpatterns = [
    url(r'^$', views.list_index, name='index'),
    url(r'^/login$', views.login_index, name='login'),
]

info/urls.py
from django.conf.urls import url
from info import views
urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^info/add$', views.add_handler, name='add_handler'),

    url(r'^edit$', views.edit_index, name='edit'),
    url(r'^edit/save$', views.edit_handler, name='edit_handler'),
]

infocollect/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin', include('control.urls', app_name='control', namespace='control')),
    url(r'^', include('info.urls', app_name='info', namespace='info')),
    # url(r'^admin/$', include('control.urls', app_name='control', namespace='control')),
]

control/models.py
from django.db import models

# Create your models here.

info/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    name = models.TextField(max_length=20)
    classname = models.TextField(max_length=50, blank=True, default='')
    phone = models.TextField(max_length=12)
    qq = models.TextField(max_length=12)
    dorm = models.TextField(max_length=50)
    birthday = models.TextField(max_length=50)
    place = models.TextField(max_length=100)
    add_time = models.DateTimeField(auto_now_add=True)
    height = models.TextField(max_length=10, blank=True, default='')
    sex = models.TextField(max_length=6, blank=True, default='')
    weight = models.TextField(max_length=10, blank=True, default='')
    size = models.TextField(max_length=10, blank=True, default='')

control/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from info.models import Person
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required(login_url='admin/login')
def list_index(request):
    people = Person.objects.all()
    return render(request, 'control/index.html', {'people': people})


def login_index(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/admin')
        else:
            return render(request, 'control/login.html', {'msg': '账户或密码错误'})
    else:
        return render(request, 'control/login.html')

info/views.py
from django.shortcuts import render
from info.models import Person

# Create your views here.
def index(request):
    return render(request, 'info/index.html', {'type': 'new'})


def add_handler(request):
    if request.method == 'POST':
        p = Person()
        p.name = request.POST.get('name')
        p.qq = request.POST.get('qq')
        p.classname = request.POST.get('classname')
        p.phone = request.POST.get('phone')
        p.dorm = request.POST.get('dorm')
        p.birthday = request.POST.get('birthday')
        p.place = request.POST.get('place')
        p.height = request.POST.get('height')
        p.sex = request.POST.get('sex')
        p.weight = request.POST.get('weight')
        p.size = request.POST.get('size')
        p.save()

        return render(request, 'info/result.html', {'result': 'ok'})
    else:
        return render(request, 'info/result.html', {'result': 'error'})


def edit_index(request):
    opt_result = False
    p = Person.objects.all()
    if request.method == 'POST':
        p = p.filter(phone=request.POST.get('phone'))
        p = p.filter(name=request.POST.get('name'))
        if len(p) != 1:
            opt_result = False
            print("Error person: len=" + str(len(p)))
        else:
            opt_result = True
    else:
        opt_result = False

    if opt_result:
        return render(request, 'info/index.html', {'type': 'edit', 'p': p[0]})
    else:
        return render(request, 'info/result.html', {'result': 'error'})


def edit_handler(request):
    opt_result = False
    if request.method == 'POST':
        p = Person.objects.filter(id=request.POST.get('id'))
        if len(p) != 1:
            opt_result = False
        else:
            p = p[0]
            p.qq = request.POST.get('qq')
            p.dorm = request.POST.get('dorm')
            p.classname = request.POST.get('classname')
            p.birthday = request.POST.get('birthday')
            p.place = request.POST.get('place')
            p.height = request.POST.get('height')
            p.sex = request.POST.get('sex')
            p.weight = request.POST.get('weight')
            p.size = request.POST.get('size')
            p.save()

            opt_result = True
    else:
        opt_result = False

    if opt_result:
        return render(request, 'info/result.html', {'result': 'ok'})
    else:
        return render(request, 'info/result.html', {'result': 'error'})

control/templates/control/index.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>info</title>
</head>
<body>
<table>
    <tr>
        <th>ID</th>
        <th>姓名</th>
        <th>性别</th>
        <th>电话</th>
        <th>班级</th>
        <th>QQ</th>
        <th>宿舍住址</th>
        <th>生日</th>
        <th>籍贯</th>
        <th>身高</th>
        <th>体重</th>
        <th>文化衫尺寸</th>
        <th>填写时间</th>
    </tr>
    {% for p in people %}
    <tr>
        <td>{{ p.id }}</td>
        <td>{{ p.name }}</td>
        <td>{{ p.sex }}</td>
        <td>{{ p.phone }}</td>
        <td>{{ p.classname }}</td>
        <td>{{ p.qq }}</td>
        <td>{{ p.dorm }}</td>
        <td>{{ p.birthday }}</td>
        <td>{{ p.place }}</td>
        <td>{{ p.height }}</td>
        <td>{{ p.weight }}</td>
        <td>{{ p.size }}</td>
        <td>{{ p.add_time|date:'Y-m-d H:i:s' }}</td>
    </tr>
    {% endfor %}
</table>
</body>
</html>

control/templates/control/login.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="" method="post">
    <div><label for="username">username</label><input type="text" name="username"></div>
    <div><label for="password">password</label><input type="password" name="password"></div>
    {% csrf_token %}
    <div>{{ msg }}</div>
    <button type="submit">登录</button>
</form>
</body>
</html>

info/templates/info/index.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/info/main.css">
	<title>填写信息</title>
</head>
<body>
<div class="container">
    <form action="{% if type == 'new' %}{% url 'info:add_handler' %}{% elif type == 'edit' %}{% url 'info:edit_handler' %}{% endif %}" method="post">
        {% if type == 'edit' %}
        <input type="hidden" name="id" value="{{ p.id }}">
        {% endif %}
        <div class="form-group">
            <label for="name">姓名</label>
            {% if type == 'new' %}
            <input class="input-box" type="text" name="name" required>
            {% else %}
            <div>{{ p.name }}</div>
            {% endif %}
        </div>
        
        <div class="form-group">
            <label for="">性别</label>
            <select class="input-box" name="sex" id="">
                <option value="男" {% if type == 'new' or p.sex == '男' %} selected{% endif %}>男</option>
                <option value="女" {% if p.sex == '女' %} selected{% endif %}>女</option>
            </select>
        </div>

        <div class="form-group">
            <label for="phone">电话</label>
            {% if type == 'new' %}
            <input class="input-box" type="text" name="phone" required>
            {% else %}
            <div>{{ p.phone }}</div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="">院系班级</label>
            <input class="input-box" type="text" name="classname" value="{{ p.classname }}" required>
        </div>

        <div class="form-group">
            <label for="phone">生日</label>
            <input class="input-box" type="text" name="birthday" value="{{ p.birthday }}" required>
        </div>

        <div class="form-group">
            <label for="qq">QQ</label>
            <input class="input-box" type="text" name="qq" value="{{ p.qq }}" required>
        </div>

        <div class="form-group">
            <label for="dorm">宿舍</label>
            <input class="input-box" type="text" name="dorm" value="{{ p.dorm }}" required>
        </div>

        <div class="form-group">
            <label for="place">籍贯</label>
            <input class="input-box" type="text" name="place" value="{{ p.place }}" required>
        </div>

        <div class="form-group">
            <label for="">身高</label>
            <input class="input-box" type="text" name="height" value="{{ p.height }}" required>
        </div>

        <div class="form-group">
            <label for="">体重(kg)</label>
            <input class="input-box" type="text" name="weight" value="{{ p.weight }}" required>
        </div>

        <div class="form-group">
            <label for="">文化衫型号</label>
            <select class="input-box" name="size" id="">
                <option value="-" {% if type == 'new' or p.size == '' %} selected{% endif %}>----</option>
                <option value="S" {% if p.size == 'S' %} selected{% endif %}>S</option>
                <option value="M" {% if p.size == 'M' %} selected{% endif %}>M</option>
                <option value="L" {% if p.size == 'L' %} selected{% endif %}>L</option>
                <option value="XL" {% if p.size == 'XL' %} selected{% endif %}>XL</option>
                <option value="XXL" {% if p.size == 'XXL' %} selected{% endif %}>XXL</option>
                <option value="XXXL" {% if p.size == 'XXXL' %} selected{% endif %}>XXXL</option>
            </select>
        </div>

        <div class="form-group">
            <label for="">文化衫型号参考</label>
            <table>
                <tr>
                    <th>型号</th>
                    <th>男</th>
                    <th>女</th>
                </tr>
                <tr>
                    <td>S</td>
                    <td>160</td>
                    <td>155~160</td>
                </tr>
                <tr>
                    <td>M</td>
                    <td>165</td>
                    <td>160~165</td>
                </tr>
                <tr>
                    <td>L</td>
                    <td>170</td>
                    <td>165~170</td>
                </tr>
                <tr>
                    <td>XL</td>
                    <td>175</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>XXL</td>
                    <td>180</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>XXXL</td>
                    <td>185</td>
                    <td>&nbsp;</td>
                </tr>

            </table>
        </div>
        {% csrf_token %}
        <button type="submit" class="submit">提交</button>
    </form>
    {% if type == 'new' %}
    <div>
        <p></p>
        <h3>已经填写？</h3>
        <form action="{% url 'info:edit' %}" method="post">
            {% csrf_token %}
            <div class="form-group"><label for="">姓名</label><input type="text" class="input-box" name="name" required></div>
            <div class="form-group"><label for="">手机号码</label><input type="text" class="input-box" name="phone" require></div>
            <button type="submit" class="submit" style="background-color: #4caf50">修改</button>
        </form>
    </div>
    {% endif %}
</div>

</body>
</html>

info/templates/info/result.html
{% extends 'info/result_base.html' %}
{% block page_title %}
        {% if result == 'ok' %}操作成功{% elif result == 'error' %}操作失败{% endif %}
{% endblock %}
{% block content %}
    {% if result == 'ok' %}
        <div class="msgbox" style="background-color: #4caf50">操作成功</div>
    {% elif result == 'error' %}
        <div class="msgbox" style="background-color: #f44336">操作失败</div>
    {% endif %}
{% endblock %}

info/templates/info/result_base.html
<!doctype html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block page_title %}{% endblock %}</title>
<link rel="stylesheet" href="/static/info/main.css">
</head>
<body>
<div class="container">
   {% block content %}
{% endblock %}
</div>

</body>
</html>